version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nisha92/nginx:v1
    container_name: nginxcontainer
    ports:
     - "8080:80"
    volumes:
     - ncvol:/var/opt/nginx
volumes:
  ncvol:
